config/routes.rb
Smartmaps::Application.routes.draw do

  resources :users
  resources :administrators
  
  get "home/index"
  get "users/index"
  post "login/login"

  root :to => "login#index"

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  belongs_to :user
  
  attr_accessible :user_id
  
  validates :user_id,  :presence => true,
					   :uniqueness => true
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  attr_accessible :birthdate, :email, :name, :username, :password, :password_confirmation

  validates :username,  :presence => true,
					    :uniqueness => true
						
  validates :email, :presence => true,
					:uniqueness => true
					
  validates_format_of   :email,
                        :with       => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i,
                        :message    => 'email must be valid'
    
  # Automatically create the virtual attribute 'password_confirmation'.
  validates :password, :presence     => true,
                       :confirmation => true,
                       :length       => { :within => 6..250 }
  
  validates_confirmation_of :password
  
					   

  #class method that authenticates a administrator, used to create a session cookie
  def self.authenticate(username, submitted_password)
    user = find_by_username(username)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  #used to authenticate a signed administrator from a signed cookie 
  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    return nil if user.nil?
    return user if user.salt == cookie_salt
  end

  #callback that occurs before a record is successfully saved (meaning it has a valud password)                      
  before_save :encrypt_password

  def has_password?(submitted_password)
    password == encrypt(submitted_password)
  end

  private

    #self keyword is required when assigning to a instance attribute
    def encrypt_password
	  self.salt = make_salt if new_record?
	  self.password = encrypt(password) if password.present?
	end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")      
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
  
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @administrators }
    end
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @administrator }
    end
  end

  # GET /administrators/new
  # GET /administrators/new.json
  def new
    @administrator = Administrator.new
	@users = User.find_by_sql("SELECT USERS.USERNAME, USERS.ID FROM USERS WHERE USERS.ID NOT IN (SELECT ADMINISTRATORS.USER_ID FROM ADMINISTRATORS)")
	
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @administrator }
	  format.json { render json: @users }
    end
  end

  # GET /administrators/1/edit
  def edit
    @administrator = Administrator.find(params[:id])
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(params[:Administrator])

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render json: @administrator, status: :created, location: @administrator }
      else
        format.html { render action: "new" }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /administrators/1
  # PUT /administrators/1.json
  def update
    @administrator = Administrator.find(params[:id])

    respond_to do |format|
      if @administrator.update_attributes(params[:administrator])
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator = Administrator.find(params[:id])
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
 
  # Finds the User with the ID stored in the session with the key
  # :current_user_id This is a common way to handle user login in
  # a Rails application; logging in sets the session value and
  # logging out removes it.
  def current_user
    @_current_user ||= session[:current_user_id] &&
      User.find_by_id(session[:current_user_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
	
  end
  
  def login
    if user = User.authenticate(params[:username], params[:password])
      # Save the user ID in the session so it can be used in
      # subsequent requests
      session[:current_user_id] = user.id
      redirect_to root_url
    end
  end
  
  # "Delete" a login, aka "log the user out"
  def destroy
    # Remove the user id from the session
    @_current_user = session[:current_user_id] = nil
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.find(:all)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to controller: 'login', action: 'index', notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
	
	respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/administrators/_form.html.erb
<%= form_for(@administrator) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @users.nil? || @users.empty?%>
   	<p> Impossible to add new administrators since all users are already administrators. </p>
  <% else %>
    <div class="field">
		<%= f.label :"Username:" %>
		<%= select("Administrator", "user_id", @users.collect {|u| [ u.username, u.id ] }, {:prompt => 'Select a user'})%>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
  <% end %>
  
  
<% end %>

app/views/administrators/index.html.erb
<h1>Listing administrators</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Email</th>
    <th>Birthdate</th>
  </tr>

<% @administrators.each do |administrator| %>
  <tr>
    <td><%= administrator.user.name %></td>
    <td><%= administrator.user.username %></td>
    <td><%= administrator.user.email %></td>
    <td><%= administrator.user.birthdate %></td>
    <td><%= link_to 'Show', administrator %></td>
    <td><%= link_to 'Destroy', administrator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Administrator', new_administrator_path %>
<%= link_to 'Home', root_path %>

app/views/administrators/new.html.erb
<h1>New administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @administrator.user.name %>
</p>

<p>
  <b>Username:</b>
  <%= @administrator.user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @administrator.user.email %>
</p>

<p>
  <b>Birthdate:</b>
  <%= @administrator.user.birthdate %>
</p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SmartMaps - Home page</title>
		<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag  "./home/main" %>
		<%= stylesheet_link_tag  "./home/popup" %>
		<%= stylesheet_link_tag  "./jquery/jquery.ui.all" %>
		<%= stylesheet_link_tag  "./jquery/datePicker" %>
		<%= javascript_include_tag  "http://maps.google.com/maps/api/js?sensor=false" %>
		<%= javascript_include_tag  "./jquery/jquery-latest" %>
		<%= javascript_include_tag  "./home/util" %>
		<%= javascript_include_tag  "./home/popup" %>
		<%= javascript_include_tag  "./home/main" %>
		<%= javascript_include_tag  "./jquery/jquery.ui.core" %>
		<%= javascript_include_tag  "./jquery/jquery.ui.datepicker" %>
	</head>
	<body onload="initialize()">
		<div class="headerDiv">
			<img src="./home/info.png" alt="" onclick="javascript:selectPopup('info')"/>
			<a href="?run=logout">Logout</a>
			<%= link_to "Users", users_path %>
			<%= link_to "Administrators", administrators_path %>
		</div>
		<hr class="headerHr"/>
		<div id="map_canvas"></div>
		<div class="functionsDiv">
			<img class="arrow" src="./home/left.png" alt="" onclick="javascript: arrowClicked(this);" onmouseover="javascript: arrowOver(this);" onmouseout="javascript: arrowOut(this);" title="Maximize map"/>
			<img src="./home/full-extent.png" alt="" onclick="javascript: fullExtent();" onmouseover="javascript: fullExtentOver(this);" onmouseout="javascript: fullExtentOut(this);" title="Full-extent"/>
			<img src="./home/move-mode.png" alt="" onclick="javascript: moveMode(this);" onmouseover="javascript: moveModeOver(this);" onmouseout="javascript: moveModeOut(this);" title="Drag&Drop Mode"/>
		</div>
		<div class="legend">
			<p class="title">Legend</p>
		</div>
		<div id="popupContact">
			<div id="uploadArea" style="display:none;">
				<a id="popupContactClose1" href="Javascript:close()">x</a>
			</div>
			<div id="informationArea" style="display:none;">
				<a id="popupContactClose2" href="Javascript:close()">x</a>
				<h1>Informations</h1> 
				<p><img class="arrow" src="assets/images/home/left.png" alt="" height="25" width="25"/><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Increase Map Size:</b> when clicked, adjusts the size of the map in your browser window, increasing the area of the map that is visible and hiding the legend.</p>
				<p><img class="arrow" src="./home/right.png" alt="" height="25" width="25"/><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Decrease Map Size:</b> when clicked, adjusts the size of the map in your browser window, decreasing the area of the map that is visible and showing back the legend.</p></p>
				<p><img src="./home/full-extent.png" alt="" height="25" width="25"/><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Full-Extent:</b> when clicked, automatically adjusts the maps's zoom to make all objects of all the categories selected in the legend visible to the user.</p>
				<p><img src="./home/move-mode.png" alt="" height="25" width="25"/><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Drag&Drop Mode:</b> when clicked once, enables the move mode where the user can drag any of the existing objects and place it in a new position, unless it is a system's default object. When the user clicks on this icon again, it is asked to confirm the operation and the changes are submitted to the database.</p>
				<p><img src="./home/GeneralMarker.png" alt="" height="25" width="25"/><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Creation Mode:</b> when the user performs a double-click in an area of the map where there is no object, a new spatial object is created. After that, the user must choose a category and fill the associated template.</p>
				<p><img src="./home/GeneralMarker.png" alt="" height="25" width="25"/><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Deletion Mode:</b> when the user performs a right-click on an existing spatial object, the object is deleted if it is not a system's default object. After, the system asks the user whether to delete the object permanently. If the user confirms the operation, the object is definitively removed, otherwise the operation is aborted.</p>
				<p><img src="./home/greenMarker.png" alt="" height="25" width="25"/><b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Directions:</b> right-click on the map and calculate directions from the clicked location until another object.</p>
			</div>
		</div>  
		<div id="backgroundPopup"></div>
	</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smartmaps</title>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login/index.html.erb
<!DOCTYPE html SYSTEM "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>Smartmaps Login</title>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag  "./login/login" %>
		<%= javascript_include_tag  "./jquery/jquery-latest" %>
		<%= javascript_include_tag  "./login/login" %>
    </head>
    <body>
		<% if !params[:notice].blank? %>
			<h2 class="notice"><%= params[:notice] %></h2>
		<% end %>
		
		<!-- Main Body Starts Here -->
		<div id="main_body">
			<!-- Form Title Starts Here -->
			<div class="form_title">
				<%= image_tag("./login/form_title.gif") %>
			</div>
			<!-- Form Title Ends Here -->
			<!-- Form Starts Here -->
			<div class="form_box">
				<%= form_tag("/login/login", :method => "post", :id => "loginForm", :name => "loginform", :enctype => "multipart/form-data", :onsubmit => "return validateForm();") do %>
				  <%= label_tag(:username, "Username: ", :class => "form_text") %>
				  <p class="form_input_BG">
					<%= text_field_tag :username, nil, :id => "userInput" %>
				  </p>
				  
				  <br/>
				  
				  <%= label_tag(:password, "Password: ", :class => "form_text") %>
				  <p id="passParagraph" class="form_input_BG">
					<%= password_field_tag(:password, nil, :id => "passwordInput", :name => "password" ) %>
				  </p>
				  
				  <br/>
				  <p class="form_login_signup_btn">
					<%= image_submit_tag("./login/login_btn.png", :title => "Login now", :name => "login", :id => "submitInput") %>				
					<%= link_to image_tag("./login/signup_btn.png", :title => "Register now", :name => "signup", :id => "signup"), :controller => "users", :action => "new" %>	
				  </p>
				<% end %>
			</div>
		</div>
    </body>
</html>

app/views/users/_editform.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.text_field :birthdate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :"Password Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'editform' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Email</th>
    <th>Birthdate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.username %></td>
    <td><%= user.email %></td>
    <td><%= user.birthdate %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>
<%= link_to 'Home', root_path %>

app/views/users/new.html.erb
<h1>Register yourself</h1>

<%= render 'form' %>

<%= link_to 'Back', :controller => "login", :action => "index" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Birthdate:</b>
  <%= @user.birthdate %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>